### ISSUE TITLE
Idee: Button/Methode einen Posten wieder zu entfernen ohne alles zu löschen 

### ISSUE THREAD

**Issue by picuber** [cafecalc/cafecalc.github.io#1]
Usecase: "größere Bestellung" und ich tippe ausversehen zu oft einen Posten. Oder Person bestellt 5 Shots und will doch nur 4.

Wenn ich mal Zeit dafür hab mach ich evtl auch selber mal nen PR

**Comment by picuber** [comment]
Zusätzliche Idee: Ich kann auch Pfand einzeln entfernen
Usecase: Eine Person gibt mir ein Glas zurück und bestellt 2 neue Getränke. Dann muss ich nur ein Mal Pfand berechnen, weil Sie ein(e) Pfand(marke) behlaten haben

(kein eigenes Issue, weil könnte evtl mit der obigen Idee kombiniert werden, falls nicht sollte das in ein neues issue umgezogen werden)

Edit: moved to #3

**Comment by stackcoder** [comment]
Implemented with commit 2e71143bcc6123bc305c7c469a42e85e102987ef

There was a small discussion offline last week which user action is the most intuitive. The consent was avoiding extra buttons and just tap and hold.
