### ISSUE TITLE
Idee: Ich kann auch Pfand einzeln entfernen

### ISSUE THREAD

**Issue by picuber** [cafecalc/cafecalc.github.io#3]
Usecase: Eine Person gibt mir ein Glas zurück und bestellt 2 neue Getränke. Dann muss ich nur ein Mal Pfand berechnen, weil Sie ein(e) Pfand(marke) behlaten haben

**Comment by stackcoder** [comment]
What about also using tap and hold here?

**Comment by picuber** [comment]
Yeah that could also work.
One thought I did have was that you could accidentally remove too much Pfand and you would need a way to add it back (or reset to all of it?). Otherwise that would work for me as well

**Comment by stackcoder** [comment]
Implemented with commit eed7133ca2318155e42273c19ff37e2b1a824ca9
